"""Extension del modelo de espacios con más detalles

Revision ID: df4df0d5d205
Revises: ccfda6bcd5d6
Create Date: 2026-01-30 12:13:18.995118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4df0d5d205'
down_revision = 'ccfda6bcd5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('price_per_hour', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('price_per_hour')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
